### PR TITLE
Fix macros and tests

### PR DESCRIPTION
**Pull request by idirall22**
- Added tests
- Fixed macro

### CODE REVIEW

**Comment by idirall22** [comment]
@ioanSL I tested the logic but not the macro it require a contract.

**Comment by ioanSL** [comment]
> @ioanSL I tested the logic but not the macro.

Gu

**Comment by ioanSL** [comment]
The changes in the macro.rs file are crashing on build NFT contract. I will have a look at it

**Comment by ioanSL** [comment]
@idirall22 I've kind of found the solution to our bug related to displaying some of the tokens. The issue is that the genesis tokens are not read in the same way as the cloned tokens. When reading a token using nft_token("0") (where we want to get token with id "0"), this function would look into the self.nft_clone_from_id tree map and attempt to find a token with id "0" in there. Since this is a genesis token, it won't be found generating an Err on unwrapping the result.

One solution could be to link the genesis token to itself on the self.nft_clone_from_id tree map. 
Another solution is to not modify nft_token function and create an alternative function that returns the cloned tokens. I personally prefer the second option since is more elegant and we won't modify the standard functionality.

Now I also have some concerns about this second approach which is, how does this affect the visibility of this tokens on NEAR Wallet?

**Comment by idirall22** [comment]
> n

We have to use the NEP171 interface we can not add another function to get only genesis token, I think we should use metadata and use it to query the right map
example:
if the token has metadata it means it's a genesis token so we can return it without checking nft_clone_from_id map.

**Review by idirall22 — COMMENTED** [review]
Bellissimo PR

**Pull request merged**
